server:
  port: 8082

springdoc:
  api-docs:
    path: "/api-docs"


management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: metrics,health,prometheus,info,httptrace


spring:
  graphql:

    websocket:
      path: /subscriptions
    graphiql:
      enabled: true
      path: /graphiql
    schema:
      printer:
        enabled: true

  security:
    user:
      name: user
      password: password