server:
  port: 8082

graphql:
  packages:
    - "de.rowi1de.reactive.graphql"
  subscriptions:
    endpoint: subscriptions
    keep-alive-interval: 1000

springdoc:
  api-docs:
    path: "/api-docs"


management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: metrics,health,prometheus,info,httptrace