apiVersion: v1 #
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    type: {{ .Release.Name }}
data:
  {{- range $key, $value := .Values.environment }}
  {{$key}}: {{ $value | quote }}
  {{- end }}
