name: Release & Push Helm Charts

on:
  workflow_run:
    workflows: ["Kotlin CI with Gradle, Build & Push OCI Image"]
    types: [completed]
  
jobs:
  helm-publish-and-release-charts:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Get latest Release
        id: get-latest-release
        uses: joutvhu/get-release@v1
        with:
          latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Bump to latest version
        id: semvers
        uses: WyriHaximus/github-action-next-semvers@v1
        with:
          version: ${{ steps.get-latest-release.outputs.tag_name }}
          
          
      - uses: chrnorm/deployment-action@v2.0.2
        name: Create GitHub deployment
        id: create-deployment
        with:
          token: "${{ github.token }}"
          environment-url: "https://graphql.robert-wiesner.de"
          description: graphql-reactive ${{ steps.semvers.outputs.patch }} / main-${{ github.sha }}
          sha: ${{ github.sha }}
          log-url: https://argocd.robert.wiesner/api/badge?name=graphql-reactive&revision=true
        
      - name: Helm Upgrade Docker Image Tag
        uses: endaft/action-yamler@v1.0.9
        with:
          # The path to a yaml file
          file: ./k8s/helm/values.yaml
          path: tag 
          set:  main-${{ github.sha }}
          
      - name: Upgrade helm App Version
        uses: endaft/action-yamler@v1.0.9
        with:
          # The path to a yaml file
          file: ./k8s/helm/Chart.yaml
          path: appVersion 
          set:  ${{ steps.semvers.outputs.patch }}

      - name: Upgrade helm Chart Version
        uses: endaft/action-yamler@v1.0.9
        with:
          # The path to a yaml file
          file: ./k8s/helm-app/Chart.yaml
          path: version 
          set:  ${{ steps.semvers.outputs.patch }}
          
      - name: Install helm
        uses: Azure/setup-helm@v1
          
      - name: Push helm-app chart
        uses: appany/helm-oci-chart-releaser@v0.3.0
        with:
           repository: ocpi-service
           registry: ghcr.io/${{ github.repository_owner }}
           registry_username: __token__
           registry_password: ${{ secrets.GITHUB_TOKEN }}
           name: graphq-reactive
           path: k8s/helm
           tag: ${{ steps.semvers.outputs.patch }}
          
      - name: Create Release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.semvers.outputs.patch }}
          release_name: ocpi-service ${{ steps.semvers.outputs.patch }}
          draft: false
          prerelease: false
        
      - name: Deployment Status Success
        if: success()
        uses: chrnorm/deployment-status@v1.0.0
        with:
          token: "${{ github.token }}"
          state: "success"
          deployment_id: ${{ steps.create-deployment.outputs.deployment_id }}
     
      - name: Deployment Status Failure
        if: failure()
        uses: chrnorm/deployment-status@v1.0.0
        with:
          token: "${{ github.token }}"
          state: "failure"
          deployment_id: ${{ steps.create-deployment.outputs.deployment_id }}
          
