name: Release & Push Helm Charts

on:
  workflow_run:
    workflows: ["Kotlin CI with Gradle, Build & Push OCI Image"]
    types: [completed]
    branches: 
    - main
  workflow_dispatch:
  
jobs:
  helm-publish-and-release-charts:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Get latest Release
        id: get-latest-release
        uses: joutvhu/get-release@v1
        with:
          latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Bump to latest version
        id: semvers
        uses: WyriHaximus/github-action-next-semvers@v1
        with:
          version: ${{ steps.get-latest-release.outputs.tag_name }}
          
          
      - uses: chrnorm/deployment-action@v2.0.7
        name: Create GitHub deployment
        id: create-deployment
        with:
          token: "${{ github.token }}"
          environment-url: "https://graphql.robert-wiesner.de"
          description: graphql-reactive ${{ steps.semvers.outputs.patch }} / main-${{ github.sha }}
          sha: ${{ github.sha }}
          log-url: https://argocd.robert.wiesner/api/badge?name=graphql-reactive&revision=true
        
      - name: Helm Upgrade Docker Image Tag
        uses: endaft/action-yamler@v1.1.1
        with:
          file: ./k8s/helm/values.yaml
          path: tag 
          set:  main-${{ github.sha }}
          
      - name: Upgrade helm App Version
        uses: endaft/action-yamler@v1.1.1
        with:
          # The path to a yaml file
          file: ./k8s/helm/Chart.yaml
          path: appVersion 
          set:  ${{ steps.semvers.outputs.patch }}

      - name: Upgrade helm Chart Version
        uses: endaft/action-yamler@v1.1.1
        with:
          file: ./k8s/helm/Chart.yaml
          path: version 
          set:  ${{ steps.semvers.outputs.patch }}
          

      - name: Push helm chart
        uses: appany/helm-oci-chart-releaser@v0.4.2
        with:
           repository: graphql-reactive
           registry: ghcr.io/${{ github.repository_owner }}
           registry_username: __token__
           registry_password: ${{ secrets.GITHUB_TOKEN }}
           name: graphql-reactive
           path: k8s/helm
           tag: ${{ steps.semvers.outputs.patch }}
           
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"  


      - name: Create Release
        uses: ncipollo/release-action@v1.14.0
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          tag: ${{ steps.semvers.outputs.patch }}
          commit: ${{ github.sha }}
          name: graphql-reactive ${{ steps.semvers.outputs.patch }}
          draft: false
          prerelease: false
          generateReleaseNotes: true
          removeArtifacts: true
        
      - name: Deployment Status Failure
        if: failure()
        uses: chrnorm/deployment-status@v2.0.3
        with:
          token: "${{ github.token }}"
          state: "failure"
          deployment-id: ${{ steps.create-deployment.outputs.deployment_id }} 
          
      - name: Deployment Status Success
        if: success()
        uses: chrnorm/deployment-status@v2.0.3
        with:
          token: "${{ github.token }}"
          state: "success"
          deployment-id: ${{ steps.create-deployment.outputs.deployment_id }}
          
      - name: Write original author
        run: echo ${{ github.actor }} > ${{ steps.semvers.outputs.patch }}-github.actor
        
      - name: Upload original Author
        uses: actions/upload-artifact@v4.3.4
        with:
          name: ${{ steps.semvers.outputs.patch }}-github.actor
          path: ${{ steps.semvers.outputs.patch }}-github.actor
